FROM node:14.17.1-alpine
WORKDIR /app

ENV NODE_ENV production

ARG REACT_APP_URL
ENV REACT_APP_URL=$REACT_APP_URL

COPY ./build ./build
COPY ./public ./public
COPY ./node_modules ./node_modules
COPY ./package.json ./package.json
COPY ./src ./src

EXPOSE 3000

ENV PORT 3000

CMD ["npm", "start"]​